using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Demo.Forms.Loader;

/*
* namespace：Demo.Forms
* className：frmHomePage
* 
* Version：HMI_RPxx_V001_202012
* Author：hehf
* Date：2020-12-12 11:57:58
* Desc：机械手页面
* 
* Remarks：
*/
namespace Demo.Forms.Loader
{
    public partial class frmHanderMain : DevExpress.XtraEditors.XtraForm
    {
        public frmHanderMain()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource3.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource3.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource4.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource5.Fill();
        }

        private void pictureEdit1_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void pictureEdit1_Click(object sender, EventArgs e)
        {
            bDoorEnable = !bDoorEnable;
            if (bDoorEnable)
            {
                picDoorEnable.Image = Image.FromFile(@"E:\工作\项目\02VS\资源\门禁管理红.png");
            }
            else
            {
                picDoorEnable.Image = Image.FromFile(@"E:\工作\项目\02VS\资源\门禁管理绿.png");
            }
            //pictureEdit1.Image = Image.FromFile(@"门禁管理红.png");
        }

        public bool bDoorEnable;
        private void picDoorEnable_EditValueChanged(object sender, EventArgs e)
        {

        }
        public bool bAuto_Manual;
        private void picAuto_Manual_Click(object sender, EventArgs e)
        {
            bAuto_Manual = !bAuto_Manual;
            if (bAuto_Manual)
            {
                picAuto_Manual.Image = Image.FromFile(@"E:\工作\项目\02VS\12.14\Demo\Demo\Resources\双手自动红 (1).png");

            }
            else
            {
                picAuto_Manual.Image = Image.FromFile(@"E:\工作\项目\02VS\12.14\Demo\Demo\Resources\双手自动绿.png");
            }
        }

        private void btnNegative_Limit_Click(object sender, EventArgs e)
        {

        }

        private void btnUnlock_Click(object sender, EventArgs e)
        {

        }

        bool bDropDown_Vertical = false;

        /* Button btn = new Button(bDropDown_Horizon, @"E:\工作\项目\02VS\12.14\Demo\Demo\Resources\静音 红.png", @"E:\工作\项目\02VS\12.14\Demo\Demo\Resources\静音.png", picAuto_Manual);
         */
        private void picDropDown_Vertical_Click(object sender, EventArgs e)
        {
            //  btn.Click();
            bDropDown_Vertical = !bDropDown_Vertical;
            pnlHorizon.Size = new Size(245, 145);
            pnlTransport.Size = new Size(245, 120);
            bDropDown_Horizon = bDropDown_Transport = false;
            if (bDropDown_Vertical)
            {
                // pnlVertical.Size = new Size(245, 445);
                pnlVertical.Size = new Size(245, 550);
                //  pnlOther.Visible = false;
            }
            else
            {
                pnlVertical.Size = new Size(245, 145);
                // pnlOther.Visible = true;
            }
        }

        bool bDropDown_Horizon = false;
        private void picDropDown_Horizon_Click(object sender, EventArgs e)
        {
            bDropDown_Horizon = !bDropDown_Horizon;
            pnlVertical.Size = new Size(245, 145);
            pnlTransport.Size = new Size(245, 120);
            bDropDown_Vertical = bDropDown_Transport = false;
            if (bDropDown_Horizon)
            {
                // pnlHorizon.Size = new Size(245, 360);
                pnlHorizon.Size = new Size(245, 400);
                // pnlOther.Visible = false;

            }
            else
            {
                pnlHorizon.Size = new Size(245, 145);
                //  pnlOther.Visible = true;
            }
        }

        bool bDropDown_Transport = false;
        private void picDropDown_L_Click(object sender, EventArgs e)
        {
            bDropDown_Transport = !bDropDown_Transport;
            pnlHorizon.Size = new Size(245, 145);
            pnlVertical.Size = new Size(245, 145);
            bDropDown_Vertical = bDropDown_Horizon = false;
            if (bDropDown_Transport)
            {
                // pnlTransport.Size= new Size(245,190);
                pnlTransport.Size = new Size(245, 250);
                //  pnlOther.Visible = false;

            }
            else
            {
                pnlTransport.Size = new Size(245, 120);
                // pnlOther.Visible = true;
            }
        }

        private void ucBoat11_Load(object sender, EventArgs e)
        {

        }

        private void ucBoat12_Load(object sender, EventArgs e)
        {

        }

        private void ucBoat7_Load(object sender, EventArgs e)
        {

        }

        private void ucBoat9_Load(object sender, EventArgs e)
        {

        }

        private void ucBoat8_Load(object sender, EventArgs e)
        {

        }

        private void ucBoat10_Load(object sender, EventArgs e)
        {

        }

        private void xtraTabControl1_Click(object sender, EventArgs e)
        {

        }

        private void btnMoveUp_V_Click(object sender, EventArgs e)
        {

        }

        private void btnMoveDown_V_Click(object sender, EventArgs e)
        {

        }

        private void btnBuffer6Down_Click(object sender, EventArgs e)
        {

        }

        private void btnBuffer3Down_Click(object sender, EventArgs e)
        {

        }

        private void btnTube3Down_Click(object sender, EventArgs e)
        {

        }

        private void btnBuffer6Up_Click(object sender, EventArgs e)
        {

        }

        private void btnBuffer3Up_Click(object sender, EventArgs e)
        {

        }

        private void btnTube3Up_Click(object sender, EventArgs e)
        {

        }

        private void btnNegative_Limit_V_Click(object sender, EventArgs e)
        {

        }

        private void panelControl2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void xtraTabControl1_Enter(object sender, EventArgs e)
        {
            pnlHorizon.Size = new Size(245, 145);
            pnlVertical.Size = new Size(245, 145);
            pnlTransport.Size = new Size(245, 120);
            pnlDoorLock.Size = new Size(245, 70);
            pnlOther.Size = new Size(245, 110);
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void tpInput_Paint(object sender, PaintEventArgs e)
        {

        }

        private void ucIO_Input1_Load(object sender, EventArgs e)
        {

        }

        private void labelControl28_Click(object sender, EventArgs e)
        {

        }

        private void textEdit5_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void textEdit4_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void textEdit3_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void textEdit2_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void textEdit1_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void labelControl11_Click(object sender, EventArgs e)
        {

        }

        private void tpStation_Paint(object sender, PaintEventArgs e)
        {

        }

        private void labelControl21_Click(object sender, EventArgs e)
        {

        }

        private void labelControl15_Click(object sender, EventArgs e)
        {

        }

        private void labelControl12_Click(object sender, EventArgs e)
        {

        }

        private void gcBoatManage_Click(object sender, EventArgs e)
        {

        }

        private void gridSplitContainer1Grid_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {

        }
    }
}