using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace com.CommunicationModels
{
  public static  class plcTubeNode
    {
        public static string[] stRecipePara1 = new string[] {
            "stRecipePara[1].eName			",
            "stRecipePara[1].bCondition_Check",
            "stRecipePara[1].nDuration",
            "stRecipePara[1].rTempZone1_SV",
            "stRecipePara[1].rTempZone2_SV",
            "stRecipePara[1].rTempZone3_SV",
            "stRecipePara[1].rTempZone4_SV",
            "stRecipePara[1].rTempZone5_SV",
            "stRecipePara[1].rTempZone6_SV",
            "stRecipePara[1].rTempZone7_SV",
            "stRecipePara[1].bTempRump_Enable",
            "stRecipePara[1].rTube_SetPressure",
            "stRecipePara[1].rLeakRateLimit",
            "stRecipePara[1].rSource1_Pressure",
            "stRecipePara[1].rSource2_Pressure",
            "stRecipePara[1].rMFC1_FlowRate",
            "stRecipePara[1].rMFC2_FlowRate",
            "stRecipePara[1].rMFC3_FlowRate",
            "stRecipePara[1].rMFC4_FlowRate",
            "stRecipePara[1].rMFC5_FlowRate",
            "stRecipePara[1].rMFC6_FlowRate",
            "stRecipePara[1].rMFC7_FlowRate",
            "stRecipePara[1].rMFC8_FlowRate",
            "stRecipePara[1].rMFC9_FlowRate",
            "stRecipePara[1].rMFC10_FlowRate",
            "stRecipePara[1].rMFC11_FlowRate",
            "stRecipePara[1].rMFC12_FlowRate",
            "stRecipePara[1].bOpen_Valve_1",
            "stRecipePara[1].bOpen_Valve_2",
            "stRecipePara[1].bOpen_Valve_3",
            "stRecipePara[1].bOpen_Valve_4",
            "stRecipePara[1].bOpen_Valve_5",
            "stRecipePara[1].bOpen_Valve_6",
            "stRecipePara[1].bOpen_Valve_7",
            "stRecipePara[1].bOpen_Valve_8",
            "stRecipePara[1].bOpen_Valve_9",
            "stRecipePara[1].bOpen_Valve_10",
            "stRecipePara[1].bOpen_Valve_11",
            "stRecipePara[1].bOpen_Valve_12",
            "stRecipePara[1].bOpen_Valve_13",
            "stRecipePara[1].bOpen_Valve_14",
            "stRecipePara[1].bOpen_Valve_15",
            "stRecipePara[1].bOpen_Valve_16",
            "stRecipePara[1].bOpen_Valve_17",
            "stRecipePara[1].bOpen_Valve_18",
            "stRecipePara[1].bOpen_Valve_19",
            "stRecipePara[1].bOpen_Valve_20",
            "stRecipePara[1].bOpen_Valve_21",
            "stRecipePara[1].bOpen_Valve_22",
            "stRecipePara[1].bOpen_Valve_23",
            "stRecipePara[1].bOpen_Valve_24",
            "stRecipePara[1].bTemp_Check",
            "stRecipePara[1].bFlow_Check",
            "stRecipePara[1].bPressure_Check" 
        };

        public static string[] stRecipePara2 = new string[] {
            "stRecipePara[2].eName			 ",
            "stRecipePara[2].bCondition_Check",
            "stRecipePara[2].nDuration",
            "stRecipePara[2].rTempZone1_SV",
            "stRecipePara[2].rTempZone2_SV",
            "stRecipePara[2].rTempZone3_SV",
            "stRecipePara[2].rTempZone4_SV",
            "stRecipePara[2].rTempZone5_SV",
            "stRecipePara[2].rTempZone6_SV",
            "stRecipePara[2].rTempZone7_SV",
            "stRecipePara[2].bTempRump_Enable",
            "stRecipePara[2].rTube_SetPressure",
            "stRecipePara[2].rLeakRateLimit",
            "stRecipePara[2].rSource1_Pressure",
            "stRecipePara[2].rSource2_Pressure",
            "stRecipePara[2].rMFC1_FlowRate",
            "stRecipePara[2].rMFC2_FlowRate",
            "stRecipePara[2].rMFC3_FlowRate",
            "stRecipePara[2].rMFC4_FlowRate",
            "stRecipePara[2].rMFC5_FlowRate",
            "stRecipePara[2].rMFC6_FlowRate",
            "stRecipePara[2].rMFC7_FlowRate",
            "stRecipePara[2].rMFC8_FlowRate",
            "stRecipePara[2].rMFC9_FlowRate",
            "stRecipePara[2].rMFC10_FlowRate",
            "stRecipePara[2].rMFC11_FlowRate",
            "stRecipePara[2].rMFC12_FlowRate",
            "stRecipePara[2].bOpen_Valve_1",
            "stRecipePara[2].bOpen_Valve_2",
            "stRecipePara[2].bOpen_Valve_3",
            "stRecipePara[2].bOpen_Valve_4",
            "stRecipePara[2].bOpen_Valve_5",
            "stRecipePara[2].bOpen_Valve_6",
            "stRecipePara[2].bOpen_Valve_7",
            "stRecipePara[2].bOpen_Valve_8",
            "stRecipePara[2].bOpen_Valve_9",
            "stRecipePara[2].bOpen_Valve_10",
            "stRecipePara[2].bOpen_Valve_11",
            "stRecipePara[2].bOpen_Valve_12",
            "stRecipePara[2].bOpen_Valve_13",
            "stRecipePara[2].bOpen_Valve_14",
            "stRecipePara[2].bOpen_Valve_15",
            "stRecipePara[2].bOpen_Valve_16",
            "stRecipePara[2].bOpen_Valve_17",
            "stRecipePara[2].bOpen_Valve_18",
            "stRecipePara[2].bOpen_Valve_19",
            "stRecipePara[2].bOpen_Valve_20",
            "stRecipePara[2].bOpen_Valve_21",
            "stRecipePara[2].bOpen_Valve_22",
            "stRecipePara[2].bOpen_Valve_23",
            "stRecipePara[2].bOpen_Valve_24",
            "stRecipePara[2].bTemp_Check",
            "stRecipePara[2].bFlow_Check",
            "stRecipePara[2].bPressure_Check"
          
        };

        public static string[] stRecipePara3 = new string[] {
            "stRecipePara[3].eName			 ",
            "stRecipePara[3].bCondition_Check",
            "stRecipePara[3].nDuration",
            "stRecipePara[3].rTempZone1_SV",
            "stRecipePara[3].rTempZone2_SV",
            "stRecipePara[3].rTempZone3_SV",
            "stRecipePara[3].rTempZone4_SV",
            "stRecipePara[3].rTempZone5_SV",
            "stRecipePara[3].rTempZone6_SV",
            "stRecipePara[3].rTempZone7_SV",
            "stRecipePara[3].bTempRump_Enable",
            "stRecipePara[3].rTube_SetPressure",
            "stRecipePara[3].rLeakRateLimit",
            "stRecipePara[3].rSource1_Pressure",
            "stRecipePara[3].rSource2_Pressure",
            "stRecipePara[3].rMFC1_FlowRate",
            "stRecipePara[3].rMFC2_FlowRate",
            "stRecipePara[3].rMFC3_FlowRate",
            "stRecipePara[3].rMFC4_FlowRate",
            "stRecipePara[3].rMFC5_FlowRate",
            "stRecipePara[3].rMFC6_FlowRate",
            "stRecipePara[3].rMFC7_FlowRate",
            "stRecipePara[3].rMFC8_FlowRate",
            "stRecipePara[3].rMFC9_FlowRate",
            "stRecipePara[3].rMFC10_FlowRate",
            "stRecipePara[3].rMFC11_FlowRate",
            "stRecipePara[3].rMFC12_FlowRate",
            "stRecipePara[3].bOpen_Valve_1",
            "stRecipePara[3].bOpen_Valve_2",
            "stRecipePara[3].bOpen_Valve_3",
            "stRecipePara[3].bOpen_Valve_4",
            "stRecipePara[3].bOpen_Valve_5",
            "stRecipePara[3].bOpen_Valve_6",
            "stRecipePara[3].bOpen_Valve_7",
            "stRecipePara[3].bOpen_Valve_8",
            "stRecipePara[3].bOpen_Valve_9",
            "stRecipePara[3].bOpen_Valve_10",
            "stRecipePara[3].bOpen_Valve_11",
            "stRecipePara[3].bOpen_Valve_12",
            "stRecipePara[3].bOpen_Valve_13",
            "stRecipePara[3].bOpen_Valve_14",
            "stRecipePara[3].bOpen_Valve_15",
            "stRecipePara[3].bOpen_Valve_16",
            "stRecipePara[3].bOpen_Valve_17",
            "stRecipePara[3].bOpen_Valve_18",
            "stRecipePara[3].bOpen_Valve_19",
            "stRecipePara[3].bOpen_Valve_20",
            "stRecipePara[3].bOpen_Valve_21",
            "stRecipePara[3].bOpen_Valve_22",
            "stRecipePara[3].bOpen_Valve_23",
            "stRecipePara[3].bOpen_Valve_24",
            "stRecipePara[3].bTemp_Check",
            "stRecipePara[3].bFlow_Check",
            "stRecipePara[3].bPressure_Check",
        };

        public static string[] stRecipePara4 = new string[] {
            "stRecipePara[4].eName			 ",
            "stRecipePara[4].bCondition_Check",
            "stRecipePara[4].nDuration",
            "stRecipePara[4].rTempZone1_SV",
            "stRecipePara[4].rTempZone2_SV",
            "stRecipePara[4].rTempZone3_SV",
            "stRecipePara[4].rTempZone4_SV",
            "stRecipePara[4].rTempZone5_SV",
            "stRecipePara[4].rTempZone6_SV",
            "stRecipePara[4].rTempZone7_SV",
            "stRecipePara[4].bTempRump_Enable",
            "stRecipePara[4].rTube_SetPressure",
            "stRecipePara[4].rLeakRateLimit",
            "stRecipePara[4].rSource1_Pressure",
            "stRecipePara[4].rSource2_Pressure",
            "stRecipePara[4].rMFC1_FlowRate",
            "stRecipePara[4].rMFC2_FlowRate",
            "stRecipePara[4].rMFC3_FlowRate",
            "stRecipePara[4].rMFC4_FlowRate",
            "stRecipePara[4].rMFC5_FlowRate",
            "stRecipePara[4].rMFC6_FlowRate",
            "stRecipePara[4].rMFC7_FlowRate",
            "stRecipePara[4].rMFC8_FlowRate",
            "stRecipePara[4].rMFC9_FlowRate",
            "stRecipePara[4].rMFC10_FlowRate",
            "stRecipePara[4].rMFC11_FlowRate",
            "stRecipePara[4].rMFC12_FlowRate",
            "stRecipePara[4].bOpen_Valve_1",
            "stRecipePara[4].bOpen_Valve_2",
            "stRecipePara[4].bOpen_Valve_3",
            "stRecipePara[4].bOpen_Valve_4",
            "stRecipePara[4].bOpen_Valve_5",
            "stRecipePara[4].bOpen_Valve_6",
            "stRecipePara[4].bOpen_Valve_7",
            "stRecipePara[4].bOpen_Valve_8",
            "stRecipePara[4].bOpen_Valve_9",
            "stRecipePara[4].bOpen_Valve_10",
            "stRecipePara[4].bOpen_Valve_11",
            "stRecipePara[4].bOpen_Valve_12",
            "stRecipePara[4].bOpen_Valve_13",
            "stRecipePara[4].bOpen_Valve_14",
            "stRecipePara[4].bOpen_Valve_15",
            "stRecipePara[4].bOpen_Valve_16",
            "stRecipePara[4].bOpen_Valve_17",
            "stRecipePara[4].bOpen_Valve_18",
            "stRecipePara[4].bOpen_Valve_19",
            "stRecipePara[4].bOpen_Valve_20",
            "stRecipePara[4].bOpen_Valve_21",
            "stRecipePara[4].bOpen_Valve_22",
            "stRecipePara[4].bOpen_Valve_23",
            "stRecipePara[4].bOpen_Valve_24",
            "stRecipePara[4].bTemp_Check",
            "stRecipePara[4].bFlow_Check",
            "stRecipePara[4].bPressure_Check"
        };


        static void sas() {

         


        }

    }
}
